'use strict';
const $ = (s, root = document) => root.querySelector(s);
// Navigation uses explicit history updates; disable CSS smooth scrolling so route changes never animate the viewport.
document.documentElement.style.scrollBehavior = 'auto';
const escapeHTML = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const concepts = items => `<div class="concept-grid">${items.map(([a,b]) => `<div class="concept"><b>${a}</b><p>${b}</p></div>`).join('')}</div>`;
const note = (s, warn = false) => `<div class="callout${warn?' warn':''}">${s}</div>`;
const caseBox = s => `<div class="case"><div class="case-label">🧩 场景拆解</div><p>${s}</p></div>`;
const lessons = [
  {name:'布局原则与视觉层级', short:'布局原则与视觉层级', subtitle:'先决定用户应该看到什么，再决定元素放在哪里。',
    explain:`<h3>布局，是为信息建立秩序</h3><p class="lead">好的页面能让人迅速找到重点。布局通过大小、位置、间距与对齐，告诉读者哪些信息属于一组、哪些操作最重要。</p>${caseBox('一个学习数据面板同时展示标题、统计数字和说明。如果它们一样大、挤在一起，用户就必须逐字阅读；先突出标题和关键数字，再弱化辅助文字，扫描会更轻松。')}${concepts([['01 · 层级','用标题字号、字重和位置区分主次。一个区域尽量只有一个最强的视觉焦点。'],['02 · 对齐','让同类内容共享对齐线。标题、正文与卡片边缘对齐，页面更容易扫描。'],['03 · 亲密性','相关内容靠近，不同组之间拉开距离。间距本身就是一种分组信号。'],['04 · 一致性','重复使用间距、圆角和字号规则，让用户学会一次就能理解整个页面。']])}<h3>先画出页面的区域，再处理细节</h3><p class="lead">以学习仪表盘为例：顶部说明系统身份，导航帮助用户选择任务，主内容展示统计和趋势，页脚放补充说明。先用简单矩形画出这些区域，确定主次和阅读顺序，再考虑颜色与圆角。</p><div class="case"><strong>从内容到布局的四步</strong><ol class="check-list"><li>列出内容：标题、导航、统计卡片、趋势图、说明。</li><li>按任务分组：导航一组，数据概览一组，详细分析一组。</li><li>安排位置：宽屏侧栏加主区域，窄屏按阅读顺序纵向排列。</li><li>选实现方式：HTML 表达区域，Grid 划分骨架，Flex 对齐局部控件。</li></ol></div><h3>把规则变成可复用的尺度</h3><p class="lead">可以从 4、8、16、24、32px 的间距序列开始。组内用较小间距，组间用较大间距，再根据内容和屏幕调整。这是一种设计约定，并非所有页面都必须遵守的标准。</p>${note('<strong>⭐ 关键点：</strong>留白不等于浪费空间；它能把相关信息组织成组。标题层级也要体现在 HTML 的 h1、h2、h3 结构中。')}${note('不要只靠颜色表达重要性。字号、字重、文字标签和位置应共同传达信息。',true)}`,
    code:`/* 页面区域示意（HTML）：\n<header>页面标题</header>\n<nav aria-label="主导航">导航链接</nav>\n<main>统计卡片与趋势图</main>\n<footer>补充说明</footer>\nHTML 表达结构，下面的 CSS 定义视觉规则。 */\n\n/* 先定义尺度，再把尺度应用到具体组件 */\n:root {\n  --space-sm: 8px;\n  --space-md: 16px;\n  --space-lg: 24px;\n}\n.panel { padding: var(--space-lg); }\n.panel h2 { font-size: 24px; margin: 0 0 8px; }\n.panel p { color: #64748b; margin: 0 0 24px; }\n.metrics {\n  display: grid;\n  grid-template-columns: repeat(3, minmax(0, 1fr));\n  gap: var(--space-md);\n}\n.metric strong { display: block; font-size: 28px; }`,
    why:'间距变量让页面保持一致；标题和数字使用不同字号构建阅读顺序。minmax(0, 1fr) 允许网格轨道收缩，但长文本仍需要换行策略。', task:'切换布局，观察标题、数字与辅助说明的阅读顺序。再调整留白，找到清晰但不过分松散的状态。'},
  {name:'盒模型与间距',short:'盒模型与间距',subtitle:'分清内容宽度、内边距与外边距，才能控制元素占用的空间。',
    explain:`<h3>每一个元素，都是一个盒子</h3><p class="lead">CSS 盒模型由内容（content）、内边距（padding）、边框（border）和外边距（margin）组成。背景通常覆盖内容与内边距，外边距是元素与相邻元素之间的空间。</p>${caseBox('你给卡片设置 width: 240px，再加左右各 24px 的 padding 和 6px 的 border。默认 content-box 下，卡片边框盒会变成 300px，很容易把原本放得下的三列挤出容器。')}${concepts([['content-box','width 指定内容区宽度。边框盒宽度 = width + 左右 padding + 左右 border。'],['border-box','width 包含内容、padding 与 border。布局时更容易用宽度预测实际占用。'],['padding · 内边距','控制内容与边框的距离，例如让卡片文字不贴边。'],['margin · 外边距','控制元素外侧空间。某些普通块元素的垂直外边距会折叠；Flex/Grid 子项的外边距不会这样折叠。']])}${note('<strong>计算示例：</strong>content-box：240 + 24 × 2 + 6 × 2 = 300px；border-box：边框盒仍为 240px，内容区为 180px。')}${note('border-box 的内容宽度不会小于 0；如果 padding 与 border 的总和超过指定宽度，实际盒子仍可能变大。本实验参数避免了这种极端情况。',true)}`,
    code:`/* 同时覆盖元素和伪元素 */\n*, *::before, *::after { box-sizing: border-box; }\n\n.card {\n  width: 240px;\n  padding: 24px;\n  border: 6px solid #5b8cc6;\n  margin: 16px;\n}\n/* border-box：边框盒 240px，内容区 180px\n   content-box：边框盒 300px，内容区 240px\n   本例左右外边距另占 32px */`,
    why:'统一使用 border-box 能减少宽度计算的意外。margin 不属于 width，即使使用 border-box 也需要单独考虑；在列表和网格中优先考虑 gap。',task:'改变 box-sizing、padding 和 margin，观察实际测量值。为什么 padding 增加时，有的盒子变大、有的内容区变小？'},
  {name:'Flexbox 一维布局',short:'Flexbox 一维布局',subtitle:'沿一条主轴排列元素，处理导航栏、工具栏与组件对齐。',
    explain:`<h3>先找主轴，再谈对齐</h3><p class="lead">Flexbox 主要控制一维布局。flex-direction 决定主轴方向；justify-content 控制主轴上的分布，align-items 控制交叉轴上的对齐。</p>${caseBox('可视化系统顶部有筛选器、图例与操作按钮。它们需要在一行排列并垂直居中，容器变窄时允许换行，这正适合 Flexbox。')}${concepts([['flex-direction','row 的主轴沿行方向，column 的主轴沿列方向。改变方向后，对齐属性对应的轴也随之改变。'],['justify-content','在主轴存在剩余空间时，控制起始、居中、两端等分布方式。'],['align-items','控制交叉轴对齐。stretch 只会拉伸交叉尺寸为 auto 等满足条件的项目。'],['gap 与 flex-wrap','gap 设置项目间隙；flex-wrap: wrap 允许换行。每行独立分配空间，不保证跨行列对齐。']])}${note('<strong>⭐ 关键点：</strong>space-between 分配的是剩余空间，不是固定间距。没有剩余空间时，它不会凭空增加距离。')}${note('长文本或图表可能撑开 Flex 子项。需要收缩的子项可设置 min-width: 0，并按场景处理换行或溢出。',true)}`,
    code:`.toolbar {\n  display: flex;\n  flex-direction: row;\n  align-items: center;\n  justify-content: space-between;\n  gap: 16px;\n  flex-wrap: wrap;\n}\n.toolbar__filters {\n  display: flex;\n  gap: 8px;\n  flex-wrap: wrap;\n  min-width: 0;\n}\n/* 改为 column 后，主轴变成纵向。\n   需要占据剩余空间的项目可使用 flex: 1。 */`,
    why:'align-items: center 让高度不同的控件居中对齐；wrap 让空间不足时能够换行。实验中的项目使用 flex-shrink: 0，便于观察剩余空间与换行。',task:'先切换 justify-content，再切换 align-items。尝试 column 方向，看主轴与交叉轴如何交换。'},
  {name:'Grid 二维布局',short:'Grid 二维布局',subtitle:'同时组织行与列，为卡片列表和仪表盘建立稳定的网格。',
    explain:`<h3>当行和列都重要时，使用 Grid</h3><p class="lead">Grid 通过轨道与网格线同时管理两个方向。它适合页面骨架、卡片矩阵和需要跨行跨列的内容区域。</p>${caseBox('仪表盘里有多张统计卡片和一张更重要的趋势图。用三列网格建立共同对齐线，再让趋势图跨两列，既能突出重点，也能保留秩序。')}${concepts([['repeat 与 fr','repeat(3, 1fr) 创建三条等分轨道。fr 分配可用空间，间隙会先从空间中扣除。'],['minmax(0, 1fr)','将轨道的最小尺寸设为 0，减少长内容阻止轨道收缩的问题。'],['grid-column','span 2 表示跨两列。跨度不要超过预期列数，否则可能生成额外的隐式轨道。'],['auto-fit 与 minmax','repeat(auto-fit, minmax(...)) 可根据容器宽度自动调整列数，适合卡片列表。']])}${note('<strong>选择方法：</strong>主要沿一个方向分布内容，用 Flex；需要各行共享列边界，用 Grid。它们可以嵌套使用。')}${note('网格位置不应随意颠倒有意义的阅读顺序。视觉排列与 DOM 顺序不同，会影响键盘和屏幕阅读器用户。',true)}`,
    code:`.cards {\n  display: grid;\n  grid-template-columns: repeat(3, minmax(0, 1fr));\n  gap: 16px;\n}\n.cards > :first-child { grid-column: span 2; }\n\n/* 内容驱动的自适应卡片列表 */\n.auto-cards {\n  display: grid;\n  grid-template-columns:\n    repeat(auto-fit, minmax(min(100%, 220px), 1fr));\n  gap: 16px;\n}\n/* min(100%, 220px) 避免容器小于 220px 时被最小列宽撑开。 */`,
    why:'fr 表示剩余空间中的份额，不是整页的百分比。跨列突出重点；auto-fit 根据可用宽度组织列。实验在一列状态会把首项跨度自动限制为一列。',task:'调整列数和间距，打开“首项跨两列”。切回一列，观察跨度如何被限制。'},
  {name:'响应式布局',short:'响应式布局',subtitle:'让内容适应空间，而不是把桌面页面等比例缩小。',
    explain:`<h3>屏幕变窄，信息结构也要调整</h3><p class="lead">响应式布局结合流动尺寸、弹性媒体与媒体查询，让同一份内容在不同宽度下保持可读、可操作。</p>${caseBox('桌面上的三列统计卡片，在手机上可能小得难以阅读。切换成单列，同时缩减外侧留白，比缩小所有字体更实用。')}${concepts([['移动优先','先写适合窄屏的基本样式，再用 min-width 媒体查询逐步增强。'],['内容决定断点','当导航拥挤或卡片难读时设置断点；640px 等数值是具体设计选择，不是设备分类标准。'],['流动容器','width: 100% 配合 max-width 限制大屏阅读宽度。图片常用 max-width: 100%。'],['保持可访问','不依赖悬停完成操作；提供清晰焦点、可点击控件和合理文字大小。']])}${note('<strong>本实验是真实媒体查询：</strong>预览嵌入独立 iframe。改变它的宽度，会改变内部页面的视口，触发内部 CSS 的 @media。')}${note('媒体查询读取视口宽度，不是任意父元素宽度。普通 div 改宽不会改变页面视口；组件根据父容器变化可研究 CSS 容器查询。',true)}`,
    code:`/* HTML head 中还需要：\n<meta name="viewport" content="width=device-width, initial-scale=1">\n*/\n* { box-sizing: border-box; }\n.container { width: 100%; max-width: 1100px; margin: auto; padding: 16px; }\n.cards { display: grid; grid-template-columns: 1fr; gap: 12px; }\nimg { max-width: 100%; height: auto; }\n\n@media (min-width: 640px) {\n  .container { padding: 24px; }\n  .cards { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n}\n/* 在 639px 与 640px 之间检查临界状态。 */`,
    why:'基础样式提供单列布局，达到 640px 才启用三列。预览区域在小屏下允许横向滚动，避免大尺寸实验撑开整个课程页面。',task:'拖动宽度滑块，重点比较 639px 与 640px。观察列数和留白的变化，而不是只看字体有没有变小。'},
  {name:'综合案例与对错对比',short:'综合案例与布局复盘',subtitle:'将层级、间距、Flex 与 Grid 组合成一个可视化系统。',
    explain:`<h3>从“放得下”走向“看得懂”</h3><p class="lead">布局没有脱离场景的唯一答案。综合设计要同时考虑任务优先级、内容密度、阅读顺序和使用设备。</p>${caseBox('设计一个学习数据仪表盘：左侧提供导航，右侧先显示标题与统计，再展示学习趋势。数字用于快速概览，趋势图用于进一步分析。实验数据仅用于演示，不代表真实学习记录。')}${concepts([['页面骨架 · Grid','侧栏与主内容形成两列，主区域使用 minmax(0, 1fr) 避免宽内容撑开页面。'],['局部对齐 · Flex','标题与辅助时间说明在一行对齐；空间不足时允许换行。'],['统一节奏 · 间距','使用一致的卡片内边距和区域间距，以留白区分导航、概览与图表。'],['任务优先 · 层级','导航保持安静，统计数字突出，图表使用一致的色彩编码。']])}<h3>提交前的布局自查</h3><ul class="check-list"><li>第一次打开，能否快速看出页面的主题与主要信息？</li><li>相关区域是否对齐，组内与组间距离是否清楚？</li><li>标题变长、卡片增多时，是否出现溢出？</li><li>手机宽度下内容是否仍可读，按钮能否点击？</li><li>能否用键盘访问目录、标签与实验控件？</li></ul>${note('<strong>⭐ 实践：</strong>先只修改一个维度，观察影响，再组合改进。不要把视觉漂亮当作唯一标准：好布局首先支持用户完成任务。')}`,
    code:`.dashboard {\n  display: grid;\n  grid-template-columns: 180px minmax(0, 1fr);\n  gap: 24px;\n  padding: 24px;\n}\n.dashboard__heading {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  flex-wrap: wrap;\n  gap: 12px;\n}\n.metrics { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; }\n@media (max-width: 640px) {\n  .dashboard { grid-template-columns: 1fr; padding: 16px; }\n  .metrics { grid-template-columns: 1fr; }\n}`,
    why:'这段是可用于完整页面的骨架；下方缩略演示聚焦层级与间距，保留侧栏便于对比。完整页面的窄屏布局应按代码折成单列。',task:'在“拥挤布局”和“整理后”之间切换，对照阅读顺序。然后修改整理后的区域间距，观察过密和过疏的差别。'}
];
const enrichment=lessons.map((l,i)=>({icon:['◈','▦','↔','▥','⌁','✦'][i],summary:['先建立阅读顺序，再决定视觉样式。','盒模型决定元素真正占据多少空间。','Flexbox 沿一条轴分配剩余空间。','Grid 同时管理行与列的共同边界。','响应式布局应优先保证内容可读。','综合布局服务于用户任务，而非装饰。'][i]}));
const quizHTML=i=>`<div class="quick-check"><span>⚡ 快速判断</span><p>${['最重要的信息应该拥有最强的视觉层级。','width: 240px 是否等于边框盒宽度？','space-between 分配的是剩余空间。','Grid 更适合同时控制行和列。','640px 是本例断点，不是所有设备的标准。','好布局首先支持用户完成任务。'][i]}</p><button class="check-answer btn" data-answer="${i}">显示提示</button><em hidden>✓ 试着在“演示”中验证这个判断。</em></div>`;
function bindQuiz(){document.querySelectorAll('.check-answer').forEach(b=>b.addEventListener('click',()=>{b.nextElementSibling.hidden=false;b.textContent='已理解 ✓';b.disabled=true;}));}
const stats = () => `<div class="mini-stats"><div class="mini-stat">学习时长<b>24.5 <small>h</small></b></div><div class="mini-stat">完成实验<b>18</b></div><div class="mini-stat">本周进度<b>86<small>%</small></b></div></div>`;
const select = (id, label, values) => `<label>${label}<select id="${id}">${values.map(v=>`<option value="${Array.isArray(v)?v[0]:v}">${Array.isArray(v)?v[1]:v}</option>`).join('')}</select></label>`;
const range = (id,label,min,max,value) => `<label>${label} <output id="${id}-out">${value}px</output><input type="range" id="${id}" min="${min}" max="${max}" value="${value}"></label>`;
const preview = (body, label='LIVE PREVIEW') => `<div class="preview"><div class="preview-bar"><span>● ● ● &nbsp; ${label}</span><span>交互实验</span></div>${body}</div>`;
const tiles = n => Array.from({length:n},(_,i)=>`<div class="tile">0${i+1}</div>`).join('');
let current = 0, tab = 'explain';
let english=false;
const wordMap={'学习目录':'Learning sections','先理解，再动手':'Understand first, then practice','阅读原理，查看关键代码，最后在实验中改变一个参数。':'Read the principle, inspect the code, then change one parameter.','参考资料与说明 ↗':'References and notes ↗','上一节':'Previous','下一节':'Next','讲解':'Explain','关键代码':'Code','演示':'Demo','从原则到实现':'From principle to implementation','带着问题去实验':'Try it with a question','核心示例 · 可以把这些规则应用到自己的页面':'A focused example you can reuse in your own page.','试一试 ↗':'Try it ↗','交互实验':'Interactive lab','重置实验 ↺':'Reset ↺','信息组织':'Information structure','有序布局':'Ordered layout','弱层级 / 拥挤布局':'Weak hierarchy / crowded','内容留白':'Content whitespace','盒模型':'Box model','内边距':'Padding','外边距':'Margin','布局方案':'Layout option','整理后':'Refined','拥挤布局':'Crowded','区域间距':'Section spacing','列数':'Columns','首项跨两列':'First item spans two columns','开启':'On','关闭':'Off','预览视口宽度':'Preview viewport','手机 375':'Mobile 375','断点前 639':'Before breakpoint 639','断点后 640':'After breakpoint 640','为什么这样写':'Why this works','快速判断':'Quick check','显示提示':'Show hint','已理解 ✓':'Understood ✓','本节重点':'Remember this','去实验 ↗':'Try the demo ↗'};
Object.assign(wordMap,{'上一章':'Previous section','下一章':'Next section','学习路线':'Learning path','你将学会什么':'What you will learn','如何使用本专题':'How to use this topic','网页页面布局':'Web page layout','本周学习概览':'Weekly learning overview','把注意力留给重要的信息 · 演示数据':'Focus on what matters · Demo data','学习时长':'Study time','完成实验':'Labs completed','本周进度':'Weekly progress','每日学习时长':'Daily study time','学习数据概览':'Learning overview','本周 · 演示数据':'This week · Demo data','每天学习时长':'Daily study time','当前：':'Current:','改进：':'Improved:','问题：':'Issue:','设置':'Set','内容区域':'Content area','从这里开始':'Start here','提交物':'Submission','参考资料':'References'});
Object.assign(wordMap,{'把内容拆成导航、主内容与辅助区域；运用层级、对齐和留白；选择 Flexbox 或 Grid；检查手机上的布局。':'Divide content into navigation, primary content and supporting areas; use hierarchy, alignment and whitespace; choose Flexbox or Grid; check the layout on mobile.','每节按“文字讲解 → 关键代码 → 交互演示”学习。调整参数后，尝试解释变化的原因，再应用到自己的页面。':'Study each section through explanation, key code and interactive demo. Change a parameter, explain the result, then apply it to your own page.','最重要的信息应该拥有最强的视觉层级。':'The most important information should have the strongest visual hierarchy.','width: 240px 是否等于边框盒宽度？':'Does width: 240px equal the border-box width?','space-between 分配的是剩余空间。':'space-between distributes leftover space.','Grid 更适合同时控制行和列。':'Grid is suited to controlling rows and columns together.','640px 是本例断点，不是所有设备的标准。':'640px is this example’s breakpoint, not a universal device standard.','好布局首先支持用户完成任务。':'A good layout first helps users complete their task.','MDN · Flexbox 布局 ↗':'MDN · Flexbox ↗','MDN · Grid 布局 ↗':'MDN · Grid ↗','MDN · 媒体查询 ↗':'MDN · Media queries ↗','NN/g · 视觉层级 ↗':'NN/g · Visual hierarchy ↗','老师的课程网站 · 结构参考 ↗':'Teacher reference site · Structure ↗','学生学习作品 · 独立制作，非教师官方章节':'Student work · Independent project, not an official teacher chapter'});
Object.assign(wordMap,{'跳到课程内容':'Skip to content','本专题重点是':'This topic focuses on','学完后，你将能说明布局为什么这样设计，并实现一个结构清晰的页面。':'After this topic, you can explain layout decisions and build a clear page.','网页开发初学者':'web development beginners','老师的参考网站':'Teacher reference site'});
Object.assign(wordMap,{'LEARN / 学习':'LEARN / Learn','本周 · Demo数据':'This week · Demo data','每日学习时长':'Daily study time','统一对齐线，突出数字，弱化辅助文字；区域间距':'Align shared edges, emphasize numbers, and soften supporting text; section spacing','此处为缩略示意，数据不代表真实记录。':'This is a compact illustration; the data is not a real record.','橙色包装层模拟外边距，便于着色观察':'The orange wrapper represents the margin area for visual inspection.','加载中':'Loading','重新加载':'Reload','数据':'Data','本周':'This week','学习':'Learning','记录':'records','我的实验':'My labs','每日':'Daily','小时':'hours','内容宽度':'content width','边框盒':'border box','含左右外间距':'including horizontal margins'});
Object.assign(wordMap,{'标题':'Title','统计数字':'Key numbers','辅助文字':'Supporting text','相关信息通过卡片分组':'Related information is grouped by cards','实测边框盒':'Measured border box','内容区':'Content area','首项':'First item','三列生效':'three columns active','容器':'Container','超出外层区域时可横向滚动查看':'Scroll horizontally when the preview exceeds its frame','概览':'Overview','导航':'Navigation','趋势图':'Trend chart','侧栏':'Sidebar','间距':'Spacing','本周 ·':'This week ·'});
function translateTextNodes(){const root=document.body;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);const ordered=Object.entries(wordMap).sort((a,b)=>b[0].length-a[0].length);nodes.forEach(n=>{if(!n.parentElement||['SCRIPT','STYLE'].includes(n.parentElement.tagName))return;let v=n.nodeValue;if(english)for(const [zh,en] of ordered)v=v.split(zh).join(en);else{for(const [zh,en] of ordered)v=v.split(en).join(zh);}n.nodeValue=v;});}
const i18nObserver=new MutationObserver(()=>{if(english)translateTextNodes();});
i18nObserver.observe(document.body,{subtree:true,childList:true});
const staticCopy={
 '.brand':'Web Layout Lab', '#overview-title':'How to build a clear, beautiful web layout?', '.overview-lead':'A beginner-friendly tutorial on dividing page regions, organizing information, writing layout code, and adapting pages to different screens.',
 '.overview>h3':'Learning path', '.overview-prereq':'For beginners. HTML defines structure, CSS controls layout, and JavaScript powers the interactive experiments.', '.start-learning':'Start section 1: Layout principles →',
 '.nav-label':'Learning sections', '.learning-note strong':'Understand first, then practice', '.learning-note p':'Read the principle, inspect the code, then change one parameter in the experiment.', '.reference':'References and notes ↗',
 '#deliverables-title':'From learning to sharing', '.sources h2':'References', '.sources p:not(.eyebrow)':'Use real examples to understand the rules, then verify details in the standards.', 'footer':'Visualization Introduction · Web Layout Lab'
};
const zhCopy={'.brand':'网页布局学习专题 Web Layout Lab','#overview-title':'如何把一个网页布局得清晰、美观？','.overview-lead':'这是一份面向初学者的网页布局教程。学习如何划分页面区域、组织信息、编写布局代码，并让页面适应不同屏幕。','.overview>h3':'学习路线','.overview-prereq':'适合人群：网页开发初学者。代码示例使用 HTML 与 CSS；HTML 定义内容结构，CSS 决定排版样式，JavaScript 驱动交互实验。','.start-learning':'开始第 1 节：布局原则与视觉层级 →','.nav-label':'学习目录','.learning-note strong':'先理解，再动手','.learning-note p':'阅读原理，查看关键代码，最后在实验中改变一个参数。','.reference':'参考资料与说明 ↗','#deliverables-title':'从学习到展示 / From learning to sharing','.sources h2':'参考资料','.sources p:not(.eyebrow)':'以实际案例理解规则，再回到标准文档核对细节。','footer':'《可视化导论》课程作业 · 网页布局学习专题'};
function renderStaticLanguage(){
 document.querySelectorAll('.course-links a').forEach((a,i)=>{a.textContent=english?['Learning goals','Start learning','References','Teacher reference ↗'][i]:['学习目标与目录','开始学习','参考资料','老师的参考网站 ↗'][i];});
 document.querySelector('.hero h1').textContent=english?'Web page layout':'网页页面布局';document.querySelector('.hero-desc').textContent=english?'From visual order to code, place every element with purpose.':'从视觉秩序到代码实现，让每一个元素各就其位。';
 document.querySelector('.hero-meta').innerHTML=english?'<span>6 sections</span><span>6 interactive labs</span><span>HTML · CSS · JavaScript</span>':'<span>6 个小节</span><span>6 个交互实验</span><span>HTML · CSS · JavaScript</span>';
 for(const [sel,text] of Object.entries(staticCopy)){const e=document.querySelector(sel);if(e)e.textContent=english?text:zhCopy[sel]||e.textContent;}
 document.querySelector('.deliverables').innerHTML=english?'<p class="eyebrow">SUBMISSION</p><h2 id="deliverables-title">From learning to sharing</h2><div class="deliverable-grid"><div><b>01 · Web link</b><p>Published GitHub Pages or static site URL.</p></div><div><b>02 · Source code</b><p>A ZIP containing HTML, CSS and JavaScript.</p></div><div><b>03 · Walkthrough video</b><p>Keep it under five minutes and explain the design decisions.</p></div><div><b>04 · Notes</b><p>Describe the structure, theory, interaction and design choices.</p></div></div>':'<p class="eyebrow">SUBMISSION / 提交物</p><h2 id="deliverables-title">从学习到展示 / From learning to sharing</h2><div class="deliverable-grid"><div><b>01 · 网页链接 / Web link</b><p>发布后的 GitHub Pages 或其他静态网站地址。</p></div><div><b>02 · 源代码 / Source code</b><p>将网站文件打包为 ZIP，包含 HTML、CSS 和 JavaScript。</p></div><div><b>03 · 讲解视频 / Walkthrough</b><p>原则上不超过 5 分钟，展示亮点并说明设计理由。</p></div><div><b>04 · 说明文档 / Notes</b><p>说明页面结构、理论依据、交互演示和自己的设计决策。</p></div></div>';
}
const enTitles=['Layout principles and visual hierarchy','The box model and spacing','Flexbox: one-dimensional layout','Grid: two-dimensional layout','Responsive layout','Case study and critique'];
const enSubs=['Decide what users should see first, then decide where elements belong.','Understand content width, padding, border, and margin.','Arrange items along one axis for navigation and toolbars.','Organize rows and columns for cards and dashboards.','Adapt content to available space instead of shrinking everything.','Combine hierarchy, spacing, Flexbox, and Grid in one system.'];
const enSummary=['Establish reading order before visual styling.','The box model determines the space an element really occupies.','Flexbox distributes space along one axis.','Grid manages shared row and column boundaries.','Responsive layout protects readability first.','A good layout serves the user task, not decoration.'];
const enExplain=['A strong layout gives information an order. Size, position, spacing and alignment tell users what belongs together. Start with content groups, then choose the layout tool.','Every element is a box made of content, padding, border and margin. Understanding the box model prevents overflow and unexpected card sizes.','Flexbox arranges items along one main axis. Direction chooses the axis, justify-content distributes free space, and align-items controls the cross axis.','Grid controls rows and columns together. Shared tracks align cards and dashboards; spans create emphasis.','Responsive design adapts information to available space. Start with a readable narrow layout, then enhance it with media queries.','A complete page combines hierarchy, spacing, Grid and Flexbox around a user task. Review reading order, overflow, keyboard access and small-screen behavior.'];
const enCode=['Define spacing tokens and use a heading hierarchy with a grid for related metrics.','Use border-box when width should describe the complete border box.','Use one axis for distribution, gap for spacing, and wrap when a row may run out of room.','Use minmax(0, 1fr) for tracks that must shrink, and span columns only for emphasis.','Use a single-column base and add columns at a content-driven breakpoint.','Use Grid for the page shell and Flexbox for local alignment.'];
const enDemo=['Change hierarchy and whitespace, then explain which signal makes the title easier to scan.','Switch box-sizing and measure the border box.','Change direction, alignment and distribution to see both axes.','Change column count and span to see shared boundaries.','Compare 639px and 640px to observe the media query transition.','Compare dashboard states and identify which changes improve task focus.'];
function bilingualCode(code,index){if(!english)return code;const notes=['Layout regions and spacing tokens','Box sizing and declared width','Main-axis distribution and cross-axis alignment','Shared grid tracks and column spans','Mobile-first base styles and breakpoint enhancement','A responsive page shell combining Grid and Flexbox'];return `/* ${notes[index]} | 中文说明见下方注释 */\n`+code.split('\n').map(line=>/[\u4e00-\u9fff]/.test(line)?`${line}  /* English: ${notes[index]} */`:line).join('\n');}
function updateLanguage(){document.body.classList.toggle('english',english);document.documentElement.lang=english?'en':'zh-CN';$('#lang-toggle').setAttribute('aria-pressed',String(english));$('#lang-toggle').textContent=english?'EN / 中文':'中文 / EN';renderStaticLanguage();if(location.hash.match(/^#section-[1-6]$/))render();else buildOverview();translateTextNodes();}
function buildOverview(){
 $('#overview-cards').innerHTML=lessons.map((l,i)=>`<a class="overview-card" href="#section-${i+1}"><div class="topic-art art-${i}" aria-hidden="true"><i></i><i></i><i></i><i></i></div><span class="section-kicker">0${i+1}</span><h3>${english?enTitles[i]:l.name}</h3><p>${english?enSubs[i]:l.subtitle}</p><span class="card-meta">${english?'Explain · Code · Demo →':'讲解 · 关键代码 · Demo →'}</span></a>`).join('');
}
function demoHTML(i) {
  const reset='<button class="btn" id="reset">重置实验 ↺</button>';
  if(i===0) return `<div class="controls">${select('order','信息组织',[['ordered','有序布局'],['unordered','弱层级 / 拥挤布局']])}${range('space','内容留白',8,40,24)}${reset}</div>${preview(`<div class="mini-page" id="hierarchy"><h4>本周学习概览</h4><p>把注意力留给重要的信息 · 演示数据</p>${stats()}</div>`)}<div class="lab-result" id="result"></div>`;
  if(i===1) return `<div class="controls">${select('sizing','盒模型',['border-box','content-box'])}${range('padding','内边距',0,40,24)}${range('margin','外边距',0,30,16)}${reset}</div>${preview('<div class="box-stage"><div class="margin-box" id="margin-box"><div class="box-demo" id="box"><span>内容区域</span></div></div></div>')}<div class="legend"><span style="--swatch:#fff0d9">margin</span><span style="--swatch:#5b8cc6">border：6px</span><span style="--swatch:#c7e0ff">padding</span><span style="--swatch:#fff">content</span></div><div class="lab-result" id="result" aria-live="polite"></div>`;
  if(i===2) return `<div class="controls">${select('direction','flex-direction',['row','column'])}${select('justify','justify-content',['flex-start','center','space-between','space-evenly'])}${select('align','align-items',['center','flex-start','flex-end','stretch'])}${select('wrap','flex-wrap',['wrap','nowrap'])}${range('gap','gap',0,32,12)}${reset}</div>${preview(`<div class="flex-stage" id="flex">${tiles(4)}</div>`)}<div class="lab-result" id="result"></div>`;
  if(i===3) return `<div class="controls">${select('columns','列数',['3','2','1','4'])}${select('span','首项跨两列',[['1','关闭'],['2','开启']])}${range('gap','gap',0,32,16)}${reset}</div>${preview(`<div class="grid-stage" id="grid">${tiles(6)}</div>`)}<div class="lab-result" id="result"></div>`;
  if(i===4) return `<div class="controls">${range('width','预览视口宽度',320,960,720)}<button class="btn" data-width="375">手机 375</button><button class="btn" data-width="639">断点前 639</button><button class="btn" data-width="640">断点后 640</button>${reset}</div>${preview('<div class="frame-scroll"><iframe class="responsive-frame" id="responsive" title="响应式卡片布局预览" sandbox=""></iframe></div>','RESPONSIVE VIEWPORT')}<div class="lab-result" id="result"></div>`;
  return `<div class="controls">${select('quality','布局方案',[['good','整理后'],['bad','拥挤布局']])}${range('spacing','区域间距',8,32,16)}${reset}</div>${preview(`<div class="dashboard" id="dashboard"><aside class="dash-nav"><b>LEARN / 学习</b><span>▦ 学习概览</span><span>◷ 学习记录</span><span>□ 我的实验</span></aside><div class="dash-main"><div class="dash-title">学习数据概览<small>本周 · 演示数据</small></div>${stats()}<div class="chart">每日学习时长<div class="bars" aria-label="一周学习时长示意图">${[35,55,45,75,60,90,68].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div></div></div>`)}<div class="lab-result" id="result"></div>`;
}
function bindDemo() {
  const root=$('#panel-demo');
  if(current===4) $('#responsive').srcdoc=`<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;font:14px/1.5 system-ui,sans-serif;color:#142338}.container{width:100%;max-width:1100px;margin:auto;padding:16px}h2{font-size:20px;margin:0 0 5px}p{color:#64748b;font-size:12px;margin:0 0 15px}.cards{display:grid;grid-template-columns:1fr;gap:12px}.card{padding:12px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:6px;font-size:12px}.card b{display:block;font-size:24px;color:#2563eb}.state{font-size:11px;color:#64748b;margin-top:12px}.state:after{content:'单列 · 窄屏基础样式'}@media(min-width:640px){.container{padding:24px}.cards{grid-template-columns:repeat(3,minmax(0,1fr))}.state:after{content:'三列 · min-width: 640px 生效'}}</style><div class="container"><h2>学习概览</h2><p>同一份内容，适应不同的可用空间。</p><div class="cards"><div class="card">学习时长<b>24.5 h</b></div><div class="card">完成实验<b>18</b></div><div class="card">本周进度<b>86%</b></div></div><div class="state"></div></div></html>`;
  root.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',updateDemo));
  root.querySelectorAll('[data-width]').forEach(b=>b.addEventListener('click',()=>{$('#width').value=b.dataset.width;updateDemo();}));
  $('#reset').addEventListener('click',()=>{root.innerHTML=`<div class="lab-intro"><b>试一试 ↗</b><span>${lessons[current].task}</span></div>${demoHTML(current)}`;bindDemo();if(english)translateTextNodes();});
  updateDemo();
}
function updateDemo(event){
  const moving = event && !matchMedia('(prefers-reduced-motion: reduce)').matches
    ? [...document.querySelectorAll('#flex .tile, #grid .tile')].map(el=>{el.getAnimations().forEach(a=>a.cancel());return [el,el.getBoundingClientRect()];}) : [];
  $('#panel-demo').querySelectorAll('input[type=range]').forEach(el=>{const out=$(`#${el.id}-out`);if(out)out.textContent=el.value+'px';});
  const val=id=>$(`#${id}`).value;
  let result='';
  if(current===0){const bad=val('order')==='unordered',s=+val('space');$('#hierarchy').classList.toggle('unordered',bad);$('#hierarchy').style.padding=s+'px';result=bad?'当前：标题与正文接近同一层级，卡片间距不足。留白增大也不能独自解决层级问题。':`当前：标题 → 统计数字 → 辅助文字。内容留白 ${s}px；相关信息通过卡片分组。`;}
  if(current===1){const p=+val('padding'),m=+val('margin'),sizing=val('sizing'),box=$('#box');Object.assign(box.style,{width:'240px',padding:p+'px',boxSizing:sizing});$('#margin-box').style.padding=m+'px';const outer=box.getBoundingClientRect().width;result=`${sizing} | 设置 width: 240px | 实测边框盒: ${Math.round(outer)}px | 内容区: ${Math.round(outer-2*p-12)}px | 含左右外间距: ${Math.round(outer+2*m)}px`+ '（橙色包装层模拟外边距，便于着色观察）';}
  if(current===2){const direction=val('direction');Object.assign($('#flex').style,{flexDirection:direction,justifyContent:val('justify'),alignItems:val('align'),gap:val('gap')+'px',flexWrap:val('wrap'),height:direction==='column'?'360px':'230px'});result=`display: flex; flex-direction: ${direction}; justify-content: ${val('justify')}; align-items: ${val('align')}; gap: ${val('gap')}px; flex-wrap: ${val('wrap')};`;}
  if(current===3){const n=+val('columns'),span=Math.min(n,+val('span'));$('#grid').style.gridTemplateColumns=`repeat(${n}, minmax(0, 1fr))`;$('#grid').style.gap=val('gap')+'px';$('#grid .tile').style.gridColumn=`span ${span}`;result=`grid-template-columns: repeat(${n}, minmax(0, 1fr)); gap: ${val('gap')}px; 首项 grid-column: span ${span};`;}
  if(current===4){const w=+val('width');$('#responsive').style.width=w+'px';result=`预览视口 ${w}px → ${w>=640?'三列；@media (min-width: 640px) 生效，容器内边距 24px。':'单列；使用基础样式，容器内边距 16px。'} 超出外层区域时可横向滚动查看。`;}
  if(current===5){const bad=val('quality')==='bad',s=+val('spacing');$('#dashboard').classList.toggle('bad',bad);$('#dashboard').style.gap=bad?'1px':s+'px';$('#spacing').disabled=bad;result=bad?'问题：区域拥挤、重点不明确、导航色彩过强。切换“整理后”比较。':`改进：统一对齐线，突出数字，弱化辅助文字；区域间距 ${s}px。此处为缩略示意，数据不代表真实记录。`;}
  $('#result').textContent=result;
  moving.forEach(([el,before])=>{const after=el.getBoundingClientRect();const dx=before.left-after.left,dy=before.top-after.top;if(dx||dy)el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:340,easing:'cubic-bezier(.2,.75,.2,1)'});});
}
function setTab(next, focus=false){
  tab=next;
  document.querySelectorAll('[role=tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus();});
  ['explain','code','demo'].forEach(t=>$(`#panel-${t}`).hidden=t!==tab);
  if(tab==='demo')updateDemo();
}
function render(){
  document.body.classList.add('lesson-open');
  updateTopNav('lesson');
  $('#overview').hidden=true;$('#lesson-view').hidden=false;
  const l=lessons[current];$('#kicker').textContent=`SECTION 0${current+1} / WEB LAYOUT`;
  document.querySelectorAll('.section-link span:last-child').forEach((e,i)=>e.textContent=english?enTitles[i]:lessons[i].short);
  $('#prev').textContent=english?'← Previous':'← 上一节';$('#next').textContent=english?'Next →':'下一节 →';
  $('#title').textContent=`${current+1}. ${english?enTitles[current]:l.name}`;$('#subtitle').textContent=english?enSubs[current]:l.subtitle;
  const bodyExplain=english?`<div class="english-lesson"><h3>Why it matters</h3><p class="lead">${enExplain[current]}</p><h3>Key idea</h3><p class="lead">${enSummary[current]}</p></div>`:l.explain;
  $('#panel-explain').innerHTML=`<div class="takeaway"><span aria-hidden="true">${enrichment[current].icon}</span><div><small>${english?'Remember this':'这一节，先记住'}</small><p>${english?enSummary[current]:enrichment[current].summary}</p></div><button class="btn" id="try-now">${english?'Try the demo ↗':'去实验 ↗'}</button></div>`+bodyExplain+quizHTML(current);
  $('#try-now').addEventListener('click',()=>{setTab('demo');});
  bindQuiz();
  $('#panel-code').innerHTML=`<h3>${english?'From principle to implementation':'从原则到实现'}</h3><p class="code-desc">${english?'A focused example you can reuse in your own page.':'核心示例 · 可以把这些规则应用到自己的页面'}</p><div class="code-wrap"><button class="copy" id="copy">${english?'Copy code':'复制代码'}</button><pre><code>${escapeHTML(bilingualCode(l.code,current))}</code></pre></div>${note('<strong>⭐ '+(english?'Why this works':'为什么这样写')+'：</strong>'+(english?enCode[current]:l.why))}<h3>${english?'Try it with a question':'带着问题去实验'}</h3><p class="lead">${english?enDemo[current]:l.task}</p>`;
  $('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(bilingualCode(l.code,current));$('#copy').textContent=english?'Copied ✓':'已复制 ✓';}catch{$('#copy').textContent=english?'Select and copy':'请选中代码复制';}});
  $('#panel-demo').innerHTML=`<div class="lab-intro"><b>${english?'Try it ↗':'试一试 ↗'}</b><span>${english?enDemo[current]:l.task}</span></div>${demoHTML(current)}`;bindDemo();setTab(tab);
  document.querySelectorAll('.section-link').forEach((a,i)=>{a.classList.toggle('active',i===current);if(i===current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});
  $('#prev').disabled=current===0;$('#next').disabled=current===5;$('#page-number').textContent=`0${current+1} / 06`;
  document.title=`${current+1}. ${english?enTitles[current]:l.name} · ${english?'Web Layout Lab':'网页布局学习专题'}`;
  if(english)translateTextNodes();
}
function navigate(index){
 document.documentElement.style.overflowAnchor='none';
 document.body.style.overflowAnchor='none';
 current=Math.max(0,Math.min(5,index));tab='explain';history.pushState(null,'',`#section-${current+1}`);render();
 window.scrollTo(0,0);
 requestAnimationFrame(()=>window.scrollTo(0,0));
 setTimeout(()=>window.scrollTo(0,0),80);
}
$('#sections').innerHTML=lessons.map((l,i)=>`<a class="section-link" href="#section-${i+1}" data-index="${i}"><span class="num">0${i+1}</span><span>${l.short}</span></a>`).join('');
document.addEventListener('click',e=>{
 const a=e.target.closest('a[href^="#"]');
 if(!a)return;
 const href=a.getAttribute('href');
 if(href==='#section-1' || href==='#section-2' || href==='#section-3' || href==='#section-4' || href==='#section-5' || href==='#section-6'){
  e.preventDefault();
  a.blur();
  navigate(Number(href.slice(-1))-1);
 } else if(href==='#overview'){
  e.preventDefault();history.pushState(null,'','#overview');readHash();
 } else if(href==='#sources'){
  e.preventDefault();history.pushState(null,'','#sources');readHash();
 }
});
document.querySelectorAll('[role=tab]').forEach(b=>{b.addEventListener('click',()=>setTab(b.dataset.tab));b.addEventListener('keydown',e=>{const tabs=['explain','code','demo'];let n=tabs.indexOf(tab);if(e.key==='ArrowRight')n=(n+1)%3;else if(e.key==='ArrowLeft')n=(n+2)%3;else if(e.key==='Home')n=0;else if(e.key==='End')n=2;else return;e.preventDefault();setTab(tabs[n],true);});});
$('#prev').addEventListener('click',()=>navigate(current-1));$('#next').addEventListener('click',()=>navigate(current+1));
function updateTopNav(view){
 document.querySelectorAll('.course-links a').forEach(a=>{
  const active=a.hash===(view==='lesson'?'#section-1':view==='sources'?'#sources':'#overview');
  if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');
 });
}
function readHash(){
 const match=location.hash.match(/^#section-([1-6])$/);
 if(match){current=+match[1]-1;tab='explain';render();}
 else if(location.hash!=='#sources'){$('#overview').hidden=false;$('#lesson-view').hidden=true;document.body.classList.remove('lesson-open');document.title=english?'Web Layout Lab · Start here':'网页布局学习专题 · 从原则到实践';renderStaticLanguage();buildOverview();updateTopNav('overview');}
 else {$('#overview').hidden=false;$('#lesson-view').hidden=true;document.body.classList.remove('lesson-open');renderStaticLanguage();buildOverview();updateTopNav('sources');requestAnimationFrame(()=>document.querySelector('#sources')?.scrollIntoView({block:'start',behavior:'auto'}));}
}
buildOverview();
renderStaticLanguage();
$('#lang-toggle').addEventListener('click',()=>{english=!english;updateLanguage();});
window.addEventListener('hashchange',readHash);
window.addEventListener('popstate',readHash);readHash();
